"""
InterView AI - Firebase Service.

Handles interaction with Firebase Admin SDK, specifically for
triggering emails via the 'Trigger Email from Firestore' extension.
"""

import json
import logging
import os
from typing import Any, Dict, Optional
import firebase_admin
from firebase_admin import credentials, firestore

from src.core.config import get_settings

logger = logging.getLogger(__name__)

class FirebaseService:
    _instance = None
    _db = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(FirebaseService, cls).__new__(cls)
            cls._instance._initialize()
        return cls._instance

    def _initialize(self):
        """Initialize Firebase Admin SDK."""
        settings = get_settings()
        try:
            # Check if already initialized to avoid errors
            if not firebase_admin._apps:
                cred = None
                
                # Try 1: Load from environment variable (FIREBASE_SERVICE_ACCOUNT_JSON)
                firebase_json_env = os.getenv("FIREBASE_SERVICE_ACCOUNT_JSON")
                if firebase_json_env:
                    try:
                        cred_dict = json.loads(firebase_json_env)
                        cred = credentials.Certificate(cred_dict)
                        logger.info("✅ Firebase credentials loaded from FIREBASE_SERVICE_ACCOUNT_JSON environment variable")
                    except json.JSONDecodeError as e:
                        logger.warning(f"⚠️ Invalid JSON in FIREBASE_SERVICE_ACCOUNT_JSON: {e}")
                
                # Try 2: Load from file path (backward compatibility)
                if not cred and settings.FIREBASE_CREDENTIALS_PATH:
                    try:
                        if os.path.exists(settings.FIREBASE_CREDENTIALS_PATH):
                            cred = credentials.Certificate(settings.FIREBASE_CREDENTIALS_PATH)
                            logger.info(f"✅ Firebase credentials loaded from file: {settings.FIREBASE_CREDENTIALS_PATH}")
                        else:
                            logger.warning(f"⚠️ Firebase credentials file not found: {settings.FIREBASE_CREDENTIALS_PATH}")
                    except Exception as e:
                        logger.warning(f"⚠️ Failed to load Firebase credentials from file: {e}")
                
                # Initialize if credentials available
                if cred:
                    firebase_admin.initialize_app(cred)
                    self._db = firestore.client()
                    logger.info("✅ Firebase Admin initialized successfully")
                else:
                    logger.warning("⚠️ Firebase credentials not found. Email features disabled. Set FIREBASE_SERVICE_ACCOUNT_JSON environment variable.")
                    self._db = None
            else:
                self._db = firestore.client()
        except Exception as e:
            logger.error(f"❌ Failed to initialize Firebase: {e}")
            self._db = None

    def send_interview_report(self, to_email: str, session_summary: Dict[str, Any]) -> bool:
        """
        Trigger an email by writing to the 'mail' collection in Firestore.
        
        Args:
            to_email: Recipient email address
            session_summary: The session stats dictionary
            
        Returns:
            True if successful, False otherwise
        """
        if not self._db or not to_email:
            logger.warning("Cannot send email: Firebase not initialized or no email provided.")
            return False

        try:
            # Format the email HTML body
            html_content = f"""
            <h2>InterView AI - Session Report</h2>
            <p>Here is the summary of your recent interview practice session.</p>
            
            <h3>Session Stats</h3>
            <ul>
                <li><strong>Duration:</strong> {session_summary.get('duration_minutes', 0)} minutes</li>
                <li><strong>Questions Answered:</strong> {session_summary.get('total_questions', 0)}</li>
                <li><strong>Average Score:</strong> {session_summary.get('average_score', 0)}/10</li>
                <li><strong>Words Per Minute:</strong> {session_summary.get('average_wpm', 0)}</li>
                <li><strong>Filler Words:</strong> {session_summary.get('total_filler_words', 0)}</li>
            </ul>
            
            <p>Keep practicing to improve your skills!</p>
            <br>
            <p><em>Generated by InterView AI</em></p>
            """

            # Create document in 'mail' collection
            # This assumes you have the "Trigger Email" extension installed in Firebase
            self._db.collection("mail").add({
                "to": to_email,
                "message": {
                    "subject": f"Your Interview Report - Session {session_summary.get('session_id')}",
                    "html": html_content,
                },
                "timestamp": firestore.SERVER_TIMESTAMP
            })
            
            logger.info(f"📧 Queued interview report email for {to_email}")
            return True

        except Exception as e:
            logger.error(f"Failed to queue email: {e}")
            return False

# Global instance
firebase_service = FirebaseService()